name: 'involve-ai-matrix-build-action'
description: 'Action to help run cdk deployments in parallel'
author: 'Austin Dimmer - Involve AI'
inputs:
  templateMatchPattern:
    required: true
    description: 'Match pattern used to find CloudFormation Templates to include in the build matrix'
    default: '@(InfraStack)'
  milliseconds: # change this
    required: false
    description: 'input description here'
    default: '100'
runs:
  using: 'node12'
  main: 'dist/index.js'
